app = "frankieone-angular-app"
primary_region = "syd"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "3000"

[secrets]
  BASE_API_URL = "backend.kycaml.uat.frankiefinancial.io"
  API_CREATE_SESSION_PATH = "/auth/v2/machine-session"
  # The following secrets should be set using 'fly secrets set'
  # CUSTOMER_ID
  # CUSTOMER_CHILD_ID
  # API_KEY
  # GOOGLE_API_KEY
